### ISSUE TITLE
[BUG] Traces not registering locally with the new instrumentation technique

### ISSUE THREAD

**Issue by arthurbrenno** [Arize-ai/phoenix#4716]
**Describe the bug**
Im using a self-hosted phoenix version and playing around with some API requests. My traces are not beeing registered in localhost:6006.

**To Reproduce**
1. Create a docker-compose:
```yaml
services:
  phoenix:
    image: arizephoenix/phoenix:latest  # Ensure the Phoenix version is 4.0.0 or later
    depends_on:
      - db
    ports:
      - "6006:6006"  # Phoenix UI and OTLP HTTP collector
      - "4317:4317"  # OTLP gRPC collector
      - "9090:9090"  # Optional: Prometheus metrics port, if enabled
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres  # PostgreSQL connection URL
      - PHOENIX_WORKING_DIR=/mnt/data  # Optional: Specify working directory for Phoenix
    volumes:
      - phoenix_data:/mnt/data   # Persistent volume for Phoenix data

  db:
    image: postgres:14  # PostgreSQL version >= 14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"  # PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL database

volumes:
  phoenix_data:
    driver: local  # Persistent volume for Phoenix data
  postgres_data:
    driver: local  # Persistent volume for PostgreSQL data
```
2. Use the following versions of the dependencies:
```toml
"openinference-instrumentation-llama-index>=2",
    "opentelemetry-proto>=1.12.0",
    "arize-phoenix-otel>=0.5.1",
    "llama-index-callbacks-arize-phoenix>=0.1.6",
```

3. Use the following code to setup phoenix:
```py
from openinference.instrumentation.llama_index import LlamaIndexInstrumentor
from phoenix.otel import register

tracer_provider = register(
    project_name="default",
    endpoint="http://localhost:6006/v1/traces",
)

LlamaIndexInstrumentor().instrument(tracer_provider=tracer_provider)
```

**Screenshots**
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/954ae76b-3950-4cef-8e78-1ceca2a660a2">

<img width="1164" alt="image" src="https://github.com/user-attachments/assets/3a5b68ec-3364-41a5-b277-bf9c9c467a04">

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime uv as a package manager + python 3.10
