### ISSUE TITLE
[auth] record demo video

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#4967]
Record auth demo video for social and docs

**Comment by berkai** [comment]
Hello, thank you for the video. However, I wasn’t able to enable authentication for Kubernetes. It would be great if you could add an explanation for this in the documentation as well!

Hello, thank you for the video. However, I wasn’t able to enable authentication for Kubernetes. It would be great if you could add an explanation for this in the documentation as well!

Below are the environment variables I used.

```

        spec:
            containers:
                - args:
                      - -m
                      - phoenix.server.main
                      - serve
                  command:
                      - python
                  env:
                      - name: PHOENIX_SQL_DATABASE_URL
                        value: "postgresql://someuri?sslmode=require"
                      - name: PHOENIX_PORT
                        value: "6006"
                      - name: PHOENIX_ENABLE_PROMETHEUS
                        value: "True"
                      - name: PHOENIX_ENABLE_AUTH
                        value: "True"
                      - name: PHOENIX_SECRET
                        value: "somesecret/ok="
```
