### ISSUE TITLE
[BUG] UI unable to render the trace of litellm span

### ISSUE THREAD

**Issue by moikent** [Arize-ai/phoenix#4981]
**Describe the bug**
Arize Phoenix UI unable to render the trace properly, though it shows successfully submitted.

**To Reproduce**
1. Setup litellm proxy to send traces to Phoenix.
2. Send a request via curl / python

**Expected behavior**
Expect the trace to be rendered in textboxes on the website.

**Screenshots**
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/7df8efec-e269-471a-9808-deaa3f603173">

**Additional context**
The trace sent looked like this:
```
resource_spans {
  resource {
    attributes {
      key: "service.name"
      value {
        string_value: "litellm"
      }
    }
    attributes {
      key: "deployment.environment"
      value {
        string_value: "production"
      }
    }
    attributes {
      key: "model_id"
      value {
        string_value: "litellm"
      }
    }
    attributes {
      key: "openinference.project.name"
      value {
        string_value: "my-llm-app"
      }
    }
    attributes {
      key: "telemetry.sdk.language"
      value {
        string_value: "python"
      }
    }
    attributes {
      key: "telemetry.sdk.name"
      value {
        string_value: "opentelemetry"
      }
    }
    attributes {
      key: "telemetry.sdk.version"
      value {
        string_value: "1.27.0"
      }
    }
  }
  scope_spans {
    scope {
      name: "litellm"
    }
    spans {
      trace_id: "\356I`p\267\027a\025\252\374\230Tb\002\004]"
      span_id: "\241k\336\220\347.dT"
      parent_span_id: "\332\r\323\023\033\033\014\025"
      flags: 256
      name: "raw_gen_ai_request"
      kind: SPAN_KIND_INTERNAL
      start_time_unix_nano: 1728867358176390912
      end_time_unix_nano: 1728867359474374144
      attributes {
        key: "llm.openai.messages"
        value {
          string_value: "[{\'role\': \'user\', \'content\': \"who\'s the president of malaysia\"}]"
        }
      }
      attributes {
        key: "llm.openai.stream"
        value {
          string_value: "False"
        }
      }
      attributes {
        key: "llm.openai.extra_body"
        value {
          string_value: "{}"
        }
      }
      attributes {
        key: "llm.openai.id"
        value {
          string_value: "chatcmpl-AI3fKSOaXpf3En5jbcGBUpB1utBu6"
        }
      }
      attributes {
        key: "llm.openai.choices"
        value {
          string_value: "[{\'finish_reason\': \'stop\', \'index\': 0, \'logprobs\': None, \'message\': {\'content\': \'As of October 2023, Malaysia does not have a presidential system; it is a constitutional monarchy. The head of state is the King, known as the Yang di-Pertuan Agong. The Prime Minister is the head of government. As of this date, the Prime Minister of Malaysia is Anwar Ibrahim.\', \'refusal\': None, \'role\': \'assistant\', \'function_call\': None, \'tool_calls\': None}}]"
        }
      }
      attributes {
        key: "llm.openai.created"
        value {
          string_value: "1728867358"
        }
      }
      attributes {
        key: "llm.openai.model"
        value {
          string_value: "gpt-4o-2024-08-06"
        }
      }
      attributes {
        key: "llm.openai.object"
        value {
          string_value: "chat.completion"
        }
      }
      attributes {
        key: "llm.openai.service_tier"
        value {
          string_value: "None"
        }
      }
      attributes {
        key: "llm.openai.system_fingerprint"
        value {
          string_value: "fp_6b68a8204b"
        }
      }
      attributes {
        key: "llm.openai.usage"
        value {
          string_value: "{\'completion_tokens\': 64, \'prompt_tokens\': 13, \'total_tokens\': 77, \'completion_tokens_details\': {\'audio_tokens\': None, \'reasoning_tokens\': 0}, \'prompt_tokens_details\': {\'audio_tokens\': None, \'cached_tokens\': 0}}"
        }
      }
      status {
        code: STATUS_CODE_OK
      }
    }
    spans {
      trace_id: "\356I`p\267\027a\025\252\374\230Tb\002\004]"
      span_id: "\332\r\323\023\033\033\014\025"
      flags: 256
      name: "litellm_request"
      kind: SPAN_KIND_INTERNAL
      start_time_unix_nano: 1728867358176390912
      end_time_unix_nano: 1728867359474374144
      attributes {
        key: "llm.model_name"
        value {
          string_value: "gpt-4o"
        }
      }
      attributes {
        key: "openinference.span.kind"
        value {
          string_value: "LLM"
        }
      }
      attributes {
        key: "input.value"
        value {
          string_value: "who\'s the president of malaysia"
        }
      }
      attributes {
        key: "llm.input_messages.0.message.role"
        value {
          string_value: "user"
        }
      }
      attributes {
        key: "llm.input_messages.0.message.content"
        value {
          string_value: "who\'s the president of malaysia"
        }
      }
      attributes {
        key: "llm.invocation_parameters"
        value {
          string_value: "{\'stream\': False, \'max_retries\': 0, \'extra_body\': {}}"
        }
      }
      attributes {
        key: "output.value"
        value {
          string_value: "As of October 2023, Malaysia does not have a presidential system; it is a constitutional monarchy. The head of state is the King, known as the Yang di-Pertuan Agong. The Prime Minister is the head of government. As of this date, the Prime Minister of Malaysia is Anwar Ibrahim."
        }
      }
      attributes {
        key: "llm.output_messages.0.message.role"
        value {
          string_value: "assistant"
        }
      }
      attributes {
        key: "llm.output_messages.0.message.content"
        value {
          string_value: "As of October 2023, Malaysia does not have a presidential system; it is a constitutional monarchy. The head of state is the King, known as the Yang di-Pertuan Agong. The Prime Minister is the head of government. As of this date, the Prime Minister of Malaysia is Anwar Ibrahim."
        }
      }
      attributes {
        key: "llm.token_count.total"
        value {
          int_value: 77
        }
      }
      attributes {
        key: "llm.token_count.completion"
        value {
          int_value: 64
        }
      }
      attributes {
        key: "llm.token_count.prompt"
        value {
          int_value: 13
        }
      }
      status {
        code: STATUS_CODE_OK
      }
    }
  }
}
```

**Comment by axiomofjoy** [comment]
@moikent Thanks for using Phoenix. A few follow-up questions:

> Setup litellm proxy to send traces to Phoenix.

Can you send a code snippet to reproduce?

> Send a request via curl / python

Can you clarify what this means? In general, you do not want to sent manually created JSON requests, but should use instrumentation to submit spans.

**Comment by axiomofjoy** [comment]
I'm not sure I recognize the format of the JSON object on this issue. How did you construct?

**Comment by moikent** [comment]
@axiomofjoy 
This is my current setup. For experimentation purpose, I'm using Postman to invoke LiteLLM Proxy, which is setup to log traces to Arize Phoenix.

Postman -> LiteLLM Proxy -> Arize Phoenix 

As a user, i dont send any requests directly to Phoenix, instead it's handled by LiteLLM Proxy server.
Here's the LiteLLM config I use:

```
model_list: 
  - model_name: gpt-4o # user-facing model alias
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: openai/gpt-4o
      api_key: sk-<somekey>
      rpm: 2

litellm_settings:
  num_retries: 3 # retry call 3 times on each model_name (e.g. zephyr-beta)
  request_timeout: 10 # raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout 
  allowed_fails: 3 # cooldown model if it fails > 1 call in a minute. 
  callbacks: ["arize"]

router_settings:
  routing_strategy: simple-shuffle # Literal["simple-shuffle", "least-busy", "usage-based-routing","latency-based-routing"], default="simple-shuffle"
  # model_group_alias: {"gpt-4": "gpt-3.5-turbo"} # all requests with `gpt-4` will be routed to models with `gpt-3.5-turbo`
  num_retries: 2
  timeout: 30                                  # 30 seconds

general_settings: 
  master_key: sk-1234 
  database_url: "postgresql://postgres:postgres@127.0.0.1:5432/litellm" 

environment_variables:
    ARIZE_SPACE_KEY: "default"
    ARIZE_API_KEY: "141a****"
    ARIZE_ENDPOINT: "http://0.0.0.0:4317"
```
