### ISSUE TITLE
[BUG] When deploying Phoenix using K8S (with ingress prefix route set), static files fail to load successfully.

### ISSUE THREAD

**Issue by alexChiu127** [Arize-ai/phoenix#5254]
**Describe the bug**

We used K8s to deploy Phoenix, referring to the following method to write the deploy YAML file (SQLite with a StatefulSet, Via a Manual Manifest):
https://docs.arize.com/phoenix/deployment/kubernetes

Since our ingress has a router set to a subpath:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-virtualservice
  namespace: test
spec:
  gateways:
  - test-ingressgateway
  hosts:
  - abc.com
  - match:
    - uri:
        prefix: /phoenix
    route:
    - destination:
        host: phoenix-service
        port:
          number: 6006
```

We referred to the configuration settings article:
https://docs.arize.com/phoenix/deployment/configuration
and added the environment variable `PHOENIX_HOST_ROOT_PATH` with the value `/phoenix` to the deploy YAML file.
(If this is not done, accessing abc.com/phoenix will result in a 404 not found error for static files like js)

However, after doing this, when accessing abc.com/phoenix, my browser console still shows the following errors indicating that the js files could not be loaded:
```
modernizr.js:1 Uncaught SyntaxError: Unexpected token '<' (at modernizr.js:1:1)
vendor-three-DwGkEfCM.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**To Reproduce**
as above description

**Expected behavior**

I expect that accessing abc.com/phoenix will display the Phoenix dashboard homepage. Currently, when there is an issue, it results in a blank page.

**Screenshots**
deploy yaml:
![image](https://github.com/user-attachments/assets/120362a2-e042-49a1-be85-aa55a6aaf608)

error in browser console when access "abc.com/phoenix":
![image](https://github.com/user-attachments/assets/b067ae21-6774-4455-a765-d62256ebb64f)

**Environment (please complete the following information):**
 - OS: Windows11
 - Browser: chrome
 - Chrome Version 128.0.6613.138

**Additional context**
N/A

**Comment by RogerHYang** [comment]
Thank you for the report. This is a bit of a head scratcher. What version of Phoenix are you using? Does it work if you don't specify `PHOENIX_HOST_ROOT_PATH`? I assume you needed to specify that because you're using a load balancer proxy, correct?

**Comment by RogerHYang** [comment]
OK. i see you're specifying an ingest gateway

**Comment by RogerHYang** [comment]
I tried running it [locally](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#testing-locally-with-traefik) with traefik and `PHOENIX_HOST_ROOT_PATH` seems to working for me

<img width="1207" alt="Screenshot 2024-11-05 at 7 26 36 PM" src="https://github.com/user-attachments/assets/3a466bb8-3eb3-4698-880a-05cff7e3390a">

**Comment by Mykp3** [comment]
We are having the same exact issue on a, as it seems on the same config:

AKS and istio ingress.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: aurora-phoenix
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /prefix/
    rewrite:
      uri: /
    route:
      - destination:
          host: aurora-phoenix.namespace.svc.cluster.local
          port:
            number: 80
```

I am able to verify HTTP 200 on attempt to reach via ingress (Public FQDN), however, nothing is displayed - absolute white space with the error message inside the browser dev panel (Networking tab says index.js was successfully downloaded)  
```
 Uncaught SyntaxError: Unexpected token '<'Understand this errorAI
index.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```
 
 Adding this to the STS config did not help
             - name: PHOENIX_HOST
              value: 0.0.0.0
            - name: PHOENIX_HOST_ROOT_PATH
              value: /phoenix
