### ISSUE TITLE
[BUG]: Kubernetes Installation

### ISSUE THREAD

**Issue by danielstankw** [Arize-ai/phoenix#7624]
### Where do you use Phoenix

Local (self-hosted)

### What version of Phoenix are you using?

4.0.0

### What operating system are you seeing the problem on?

Linux

### What happened?

I am attempting to install Phoenix on K8s but with sqlite - for PoC.  
I am using slightly modified version from [here](https://docs.arize.com/phoenix/self-hosting/deployment-options/kubernetes#sqlite-with-a-statefulset)- the original version is missing the `name` field.
Below I attach the `phoenix.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phoenix
  name: phoenix
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6006
  selector:
    app: phoenix
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phoenix
  namespace: phoenix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix
  template:
    metadata:
      # Assume k8s pod service discovery for prometheus
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        app: phoenix
    spec:
      containers:
      - args:
        - -m
        - phoenix.server.main
        - serve
        command:
        - python
        env:
        - name: PHOENIX_WORKING_DIR
          value: /mnt/data
        # The version of phoenix you want should be used here
        image: docker.io/arizephoenix/phoenix:version-4.0.0
        name: phoenix
        ports:
        - containerPort: 6006
        - containerPort: 4317
        - containerPort: 9090
        volumeMounts:
        - mountPath: /mnt/data
          name: phoenix
  volumeClaimTemplates:
  - metadata:
      name: phoenix
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 8Gi
      storageClassName: ""
      volumeMode: Filesystem
```

Additionally I created PV
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: phoenix
  name: phoenix-0
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  nfs:
    path: /phoenix
    server: XXX
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: phoenix-phoenix-0
    namespace: phoenix
```

The PVC and PV are bound properly and the pod starts up but than gets into `Error` state

```
/phoenix/env/phoenix/server/main.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/phoenix/env/phoenix/server/main.py", line 199, in <module>
    port = args.port or get_env_port()
                        ^^^^^^^^^^^^^^
  File "/phoenix/env/phoenix/config.py", line 165, in get_env_port
    raise ValueError(
ValueError: Invalid value for environment variable PHOENIX_PORT: tcp://172.20.239.77:443. Value must be an integer.
```

### What did you expect to happen?

    ...

### How can we reproduce the bug?

...
